---
engines:
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "c"
ratings:
  paths:
  - "**.py"
exclude_paths:
- "letsencrypt/tests/**/*"
- "tests/**/*"
